#!/usr/bin/env python3
"""
montage_phase2.py — Visualize grids generated by Phase 2 agent.

Usage:
  python montage_phase2.py \
    --model runs/phase2_challenge/phase2_final.zip \
    --phase1_model runs/phase1_structure/phase1_final.zip \
    --n 16 --size 13 --max_steps 80 --out montage_phase2.png --deterministic
"""

import argparse
import math
import os
from typing import Any, Tuple

import numpy as np
import matplotlib.pyplot as plt

from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3 import PPO
from phase2_env import Phase2Env, EMPTY, WALL, ROBOT, OBJECT, GOAL, MOVABLE


def make_env(phase1_model_path: str, size: int, max_steps: int, phase1_deterministic: bool, seed: int, n_objects: int = 1):
    def _thunk():
        return Phase2Env(
            phase1_model_path=phase1_model_path,
            size=size,
            max_steps=max_steps,
            phase1_deterministic=phase1_deterministic,
            seed=seed,
            n_objects=n_objects
        )
    return _thunk


def decode_metrics(info: Any) -> Tuple[int, int, bool, bool, bool]:
    """Extract metrics from info."""
    d = {}
    if isinstance(info, (list, tuple)) and len(info) and isinstance(info[0], dict):
        d = info[0]
    elif isinstance(info, dict):
        d = info
    
    n_movable = int(d.get("n_movable", 0))
    relaxed_solvable = bool(d.get("relaxed_solvable", False))
    strict_solvable = bool(d.get("strict_solvable", False))
    movable_critical = bool(d.get("movable_critical", False))
    valid = int(d.get("valid", 0))
    
    return n_movable, relaxed_solvable, strict_solvable, movable_critical, valid


def grid_to_rgb(grid: np.ndarray, n_objects: int = 1) -> np.ndarray:
    """
    Map grid (H, W) tile ids → RGB image in [0,1].
    For multi-object mode, assigns distinct colors to different object-goal pairs.
    """
    H, W = grid.shape
    img = np.ones((H, W, 3), dtype=np.float32)
    
    # Base colors
    base_colors = {
        EMPTY:  (0.94, 0.94, 0.94),  # light gray
        WALL:   (0.62, 0.43, 0.34),  # brown
        ROBOT:  (0.20, 0.45, 0.95),  # blue
        MOVABLE: (0.40, 0.70, 0.40),  # green (movable obstacles)
    }
    
    # Apply base colors
    for tid, col in base_colors.items():
        img[grid == tid] = col
    
    # Handle objects and goals with distinct colors for multi-object mode
    if n_objects == 1:
        # Single-object mode: use original colors
        img[grid == OBJECT] = (0.97, 0.75, 0.25)  # orange/yellow
        img[grid == GOAL] = (0.95, 0.35, 0.75)    # magenta
    else:
        # Multi-object mode: assign distinct colors to each object-goal pair
        obj_positions = list(zip(*np.where(grid == OBJECT)))
        goal_positions = list(zip(*np.where(grid == GOAL)))
        
        # Color palette for multiple objects (distinct colors)
        object_colors = [
            (0.97, 0.75, 0.25),  # orange/yellow (object 1)
            (0.20, 0.80, 0.40),   # green (object 2)
            (0.90, 0.30, 0.30),   # red (object 3)
            (0.30, 0.50, 0.90),   # blue (object 4)
            (0.80, 0.60, 0.20),   # brown (object 5)
        ]
        goal_colors = [
            (0.95, 0.35, 0.75),   # magenta (goal 1)
            (0.20, 0.60, 0.80),   # cyan (goal 2)
            (0.80, 0.20, 0.50),   # pink (goal 3)
            (0.50, 0.30, 0.90),   # purple (goal 4)
            (0.70, 0.40, 0.60),   # rose (goal 5)
        ]
        
        # Pair objects with goals (greedy: closest pairing)
        used_goals = set()
        for i, (oy, ox) in enumerate(obj_positions):
            best_goal_idx = None
            best_dist = float('inf')
            for j, (gy, gx) in enumerate(goal_positions):
                if j in used_goals:
                    continue
                dist = abs(oy - gy) + abs(ox - gx)
                if dist < best_dist:
                    best_dist = dist
                    best_goal_idx = j
            
            if best_goal_idx is not None:
                used_goals.add(best_goal_idx)
                color_idx = min(i, len(object_colors) - 1)
                img[oy, ox] = object_colors[color_idx]
                gy, gx = goal_positions[best_goal_idx]
                img[gy, gx] = goal_colors[color_idx]
            else:
                img[oy, ox] = object_colors[0]
        
        # Color any remaining goals
        for j, (gy, gx) in enumerate(goal_positions):
            if j not in used_goals:
                color_idx = min(j, len(goal_colors) - 1)
                img[gy, gx] = goal_colors[color_idx]
    
    return img


def unwrap_base_env(vec_env) -> Any:
    """Get the underlying (non-Vec) env."""
    base = vec_env.envs[0]
    while hasattr(base, "env"):
        base = base.env
    return base


def vec_reset_compat(env: DummyVecEnv):
    """Normalize reset to return just obs."""
    out = env.reset()
    if isinstance(out, tuple) and len(out) == 2:
        obs, _ = out
        return obs
    return out


def vec_step_compat(env: DummyVecEnv, action):
    """Call env.step(action) and normalize return."""
    out = env.step(action)
    if isinstance(out, tuple):
        if len(out) == 4:
            return out
        elif len(out) == 5:
            obs, reward, terminated, truncated, info = out
            if isinstance(terminated, (list, np.ndarray)) and isinstance(truncated, (list, np.ndarray)):
                done = np.logical_or(terminated, truncated).tolist()
            else:
                done = bool(terminated or truncated)
            return obs, reward, done, info
    raise RuntimeError("Unexpected VecEnv.step() return format")


def extract_final_grid(info):
    """Extract final grid from info dict."""
    if isinstance(info, (list, tuple)) and len(info) and isinstance(info[0], dict):
        d = info[0]
    elif isinstance(info, dict):
        d = info
    else:
        return None
    return d.get("final_grid", None)


def rollout_one(env: DummyVecEnv, model: PPO, max_steps: int, deterministic: bool):
    """Run one episode to termination."""
    obs = vec_reset_compat(env)
    done = [False]
    info = [{}]
    steps = 0

    while steps < max_steps:
        action, _ = model.predict(obs, deterministic=deterministic)
        obs, reward, done, info = vec_step_compat(env, action)
        steps += 1
        if isinstance(done, (list, np.ndarray)):
            if done[0]:
                break
        else:
            if done:
                break

    final_grid = extract_final_grid(info)
    if final_grid is None:
        base = unwrap_base_env(env)
        final_grid = base.grid.copy()
    
    return final_grid, decode_metrics(info)


def main():
    ap = argparse.ArgumentParser(description="Generate montage of Phase 2 agent outputs")
    ap.add_argument("--model", type=str, required=True, help="Path to Phase 2 model .zip")
    ap.add_argument("--phase1_model", type=str, required=True, help="Path to Phase 1 model .zip")
    ap.add_argument("--n", type=int, default=16, help="Number of samples")
    ap.add_argument("--size", type=int, default=13)
    ap.add_argument("--max_steps", type=int, default=80)
    ap.add_argument("--seed", type=int, default=12345)
    ap.add_argument("--out", type=str, default="montage_phase2.png")
    ap.add_argument("--deterministic", action="store_true", help="Greedy actions")
    ap.add_argument("--stochastic", action="store_true", help="Sample actions (overrides --deterministic)")
    ap.add_argument("--phase1_deterministic", action="store_true",
                    help="Use Phase 1 model deterministically for base puzzles")
    ap.add_argument("--n_objects", type=int, default=1, help="Number of objects (and goals). Must match Phase 1/2 models. 1 = single-object, >1 = multi-object")
    ap.add_argument("--save_npy", type=str, default="", help="Optional path to save raw grids as .npy")
    
    args = ap.parse_args()
    deterministic = args.deterministic and not args.stochastic

    # Single-env vec wrapper
    env = DummyVecEnv([make_env(
        args.phase1_model,
        args.size,
        args.max_steps,
        args.phase1_deterministic,
        args.seed,
        args.n_objects
    )])

    # Load model
    model = PPO.load(args.model, env=env, device="auto")

    # Roll out n episodes
    grids, metas = [], []
    for i in range(args.n):
        g, meta = rollout_one(env, model, args.max_steps, deterministic=deterministic)
        grids.append(g)
        metas.append(meta)

    # Optional: save raw grids
    if args.save_npy:
        np.save(args.save_npy, np.stack(grids, axis=0))
        print(f"Saved raw grids to {args.save_npy}")

    # Build montage
    cols = int(math.ceil(math.sqrt(args.n)))
    rows = int(math.ceil(args.n / cols))
    fig, axes = plt.subplots(rows, cols, figsize=(cols * 4, rows * 4))
    axes = np.array(axes).reshape(rows, cols)

    for idx in range(rows * cols):
        ax = axes[idx // cols, idx % cols]
        ax.axis("off")
        if idx >= len(grids):
            continue
        img = grid_to_rgb(grids[idx], n_objects=args.n_objects)
        n_mov, relaxed, strict, critical, valid = metas[idx]
        
        # Build title
        title_parts = [f"m={n_mov}"]
        if valid:
            title_parts.append("✓")
        if critical:
            title_parts.append("CRIT")
        elif relaxed and not strict:
            title_parts.append("R-only")
        elif strict:
            title_parts.append("both")
        else:
            title_parts.append("bad")
        
        title = " ".join(title_parts)
        ax.set_title(title, fontsize=10)
        ax.imshow(img, interpolation="nearest")

    plt.tight_layout()
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    plt.savefig(args.out, dpi=150)
    print(f"Saved montage to {args.out}")
    
    # Print summary
    critical_count = sum(1 for _, _, _, critical, _ in metas if critical)
    valid_count = sum(1 for _, _, _, _, valid in metas if valid)
    print(f"\nSummary: {critical_count}/{valid_count} valid levels are movable-critical ({100.0*critical_count/max(1,valid_count):.1f}%)")


if __name__ == "__main__":
    main()

